### ISSUE TITLE
Admins not listed in the linked spreadsheet

### ISSUE THREAD

**Issue by rsbrennan-NOAA** [nmfs-opensci/GitHub-Guide#20]
In Section 2.5 (https://nmfs-opensci.github.io/GitHub-Guide/#wait-for-the-organization-invite-and-on-boarding-instructions), there is a link to a spreadsheet that should contain admins. There are no admins in this spreadsheet. For my organization (SEFSC) I cannot figure out who the admin is, so it would be helpful to keep this info up to date (or remove that it should be in that spreadsheet).

Also the linked SOPs are not consistent with the SOPs on the organization's pages (again, for SEFSC).

**Comment by eeholmes** [comment]
Thanks! I updated the links.
